DB:
    SERVER: axj1da13zk.database.windows.net
    DATABASE: Vmob_lgm695_DWHS
    USERNAME: plexure
    PASSWORD: e(AB{rK@vn7&bL)3

DIR:
    REPORT: Report
    SOURCE: Src

QUERY:
    QUERY: query.sql

Column_ID:
    - Recency
    - Frequency
    - Monetary